MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "/app/storage/models/t5_small_totto_qr2t/epoch=3-step=207.ckpt"

FASTAPI:
  WORKERS: 1
  DEBUG: False
  RELOAD: False
  HOST: '0.0.0.0'
  PORT: 4557

MISC:
  LOGGER_LEVEL: "INFO"
