MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/aris/compact_input/ablations/no_nl_query/aux_totto_qr2t/epoch=5-step=311.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "qr2t"
  GROUP: "No NL Query | CI | ARIS | T5-small | Aux | ToTTo | QR2T"
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/compact_input/ablation/no_nl_query/qr2t/dev.json"
  EVALUATION: "storage/datasets/compact_input/ablation/no_nl_query/qr2t/eval.json"
  TRAIN: "storage/datasets/compact_input/ablation/no_nl_query/qr2t/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
