MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/aris/compact_input/finetuned/t5_small/pretrained_qr2t/epoch=4-step=259.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "qr2t"
  GROUP: "No value masking | CI | ARIS | T5-small | Pretrain | QR2T"
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/compact_input/qr2t/dev.json"
  EVALUATION: "storage/datasets/compact_input/qr2t/eval.json"
  TRAIN: "storage/datasets/compact_input/qr2t/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
