MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "FILL_TOTTO_PATH"

OUTPUT:
  CHECKPOINTS_DIR: "storage/checkpoints/compact_input/finetuned/t5_base/totto_qr2t"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001
  MAX_EPOCHS: 10


DATASET:
  VALIDATION: "storage/datasets/qr2t/dev.json"
  EVALUATION: "storage/datasets/qr2t/eval.json"
  TRAIN: "storage/datasets/qr2t/train.json"

WANDB:
  RUN_NAME: "Finetune"
  GROUP: "CI | ARIS | T5-base | ToTTo | QR2T"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
