MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/full_entities/t5_small/epoch=3-step=60579.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "Evaluate | AdaFactor | T5-small"
  GROUP: "DEBUG"
  TAGS: ["DEBUG", "ToTTo", "T5", "small"]
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/totto/filtered_sampled/dev.json"
  TRAIN: "storage/datasets/totto/filtered_sampled/train.json"
  EVALUATION: "storage/datasets/totto/filtered_sampled/evaluation.json"



INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
DATALOADER:
  NUM_WORKERS: 11
