MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-small"
  PRETRAINED_MODEL_NAME: "t5-small"
  PATH_TO_CHECKPOINT: "storage/checkpoints/aris/main_experiments/finetuned/t5_small/totto_qr2t/epoch=3-step=207.ckpt"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "qr2t"
  GROUP: "DEBUG PARENT | ARIS | T5-small | ToTTo | QR2T"
  MODE: "online"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/aris/qr2t/dev.json"
  EVALUATION: "storage/datasets/aris/qr2t/eval.json"
  TRAIN: "storage/datasets/aris/qr2t/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 8
  TEST_BATCH_SIZE: 8
