MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "FILL_PATH"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

WANDB:
  RUN_NAME: "qr2t"
  GROUP: "CI | ARIS | T5-base | Pretrain | QR2T"
  MODE: "offline"
  NOTES: ""

DATASET:
  VALIDATION: "storage/datasets/qr2t/dev.json"
  EVALUATION: "storage/datasets/qr2t/eval.json"
  TRAIN: "storage/datasets/qr2t/train.json"

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
