MODEL:
  MAX_INPUT_TOKENS: 512
  MAX_OUTPUT_TOKENS: 64
  TOKENIZER_NAME: "t5-base"
  PRETRAINED_MODEL_NAME: "t5-base"
  PATH_TO_CHECKPOINT: "FILL_PATH"

#OUTPUT:
#  CHECKPOINTS_DIR: "storage/checkpoints/full_entities/t5_base"

SOLVER:
  OPTIMIZER_NAME: "AdaFactor"
  BASE_LR: 0.001

DATASET:
  TRAIN: "storage/datasets/compact_input/totto/train.json"
  VALIDATION: "storage/datasets/compact_input/totto/dev.json"
  EVALUATION: "storage/datasets/compact_input/totto/dev.json"

WANDB:
  RUN_NAME: "totto"
  GROUP: "CI | ARIS | T5-base | Pretrain | QR2T"
  MODE: "offline"
  NOTES: ""

DATALOADER:
  NUM_WORKERS: 11

INPUT:
  TRAIN_BATCH_SIZE: 7
  TEST_BATCH_SIZE: 7
